# Generated by Django 4.0.6 on 2022-12-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='YieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corn_grain_yield', models.FloatField()),
            ],
        ),
    ]
