# Generated by Django 4.0.6 on 2022-12-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='yielddata',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='weatherdata',
            table='weatherdata',
        ),
        migrations.AlterModelTable(
            name='yielddata',
            table='yieldata',
        ),
    ]
