# Generated by Django 4.0.6 on 2022-12-24 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_weatherdata_options_alter_yielddata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yielddata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yielddata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('date', 'max_temp', 'min_temp', 'precipitation')},
        ),
        migrations.AlterUniqueTogether(
            name='yielddata',
            unique_together={('date', 'corn_grain_yield')},
        ),
    ]
