# Generated by Django 4.0.6 on 2022-12-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_weatherdata_created_at_yielddata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yielddata',
            table='yielddata',
        ),
    ]
