# Generated by Django 4.0.6 on 2022-12-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0006_weatherdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='station_id',
            field=models.CharField(default='USC00110072', max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('date', 'max_temp', 'min_temp', 'precipitation', 'station_id')},
        ),
    ]
