# Generated by Django 4.0.6 on 2022-12-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0007_alter_weatherdata_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg_max_temp', models.FloatField()),
                ('avg_min_temp', models.FloatField()),
                ('total_precipitation', models.FloatField()),
                ('station_id', models.CharField(default='USC00110072', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics',
                'managed': True,
                'unique_together': {('date', 'avg_max_temp', 'avg_min_temp', 'total_precipitation', 'station_id')},
            },
        ),
    ]
