# Generated by Django 4.0.6 on 2022-12-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0008_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='avg_max_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='avg_min_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='total_precipitation',
            field=models.FloatField(null=True),
        ),
    ]
