# Generated by Django 4.0.6 on 2022-12-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0009_alter_analytics_avg_max_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='max_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='min_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='precipitation',
            field=models.FloatField(null=True),
        ),
    ]
