# Generated by Django 4.0.6 on 2022-12-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0010_alter_weatherdata_max_temp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytics',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='yielddata',
            options={'managed': True, 'ordering': ['id']},
        ),
    ]
